### PR TITLE
Switched to modxRTEbridge

### PR DESCRIPTION
**Pull request by Deesen**
I tried to comment/explain the code inline, added @todos etc.. most parameters should already work fine.

TinyMCE MINI works too ;-)..

### CODE REVIEW

**Comment by Deesen** [comment]
No time for testing? Too many 1.1-upgrades ;-)? Just asking. Let me know if you don´t like any parts of it.

**Comment by Dmi3yy** [comment]
Only I went back rest
now we have to work for a week and then come back to MODX )

**Comment by Deesen** [comment]
Just FYI, I will clean up some last parts of the code this weekend (optimizing arrays etc). I also started to add TinyMCE Inline-Mode (for Frontend-Editing) to the plugin, maybe you want to include it in next release if it works fine :-). And I would like to centralize the most important connector-functions within modxRTEbridge like:
- getTemplateChunkList()  for "Insert Template"-buttons
- getRessourceList()  for "Insert Link"-buttons
- anything else missing?

For inline-editing:
- prepareFrontendContent()
- saveFrontendContent()

Hope you like these ideas.

**Comment by Deesen** [comment]
**Inline-Mode**
requires https://github.com/modxcms/evolution/pull/548

tinyinline

Template:

```
<div id="modx_longtitle">[*longtitle*]</div>
<div id="modx_content">[*content*]</div>
```

Plugin-Configuration:
inlinesetup

Modx placeholders like Snippet-calls become protected
placeholderprotection

**Pull request merged**
